name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Check security vulnerabilities
        run: |
          bin/brakeman --no-pager
          bin/bundler-audit
      
      - name: Lint code
        run: bin/rubocop -f github

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bin/rails db:test:prepare test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
